version = 0.1
[pulpfree]
[pulpfree.deploy]
[pulpfree.deploy.parameters]
stack_name = "sam-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-alg91hobzyju"
s3_prefix = "sam-app"
region = "ca-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
profile = "pulpfree"
